### ISSUE TITLE
Estas declaraciones deberían ser privadas

### ISSUE THREAD

**Issue by evolentini** [Jr130797/CESE_TSSE-TP3#3]
Estas declaraciones no deberían estar en el `.h` sino en el `.c` ya que son declaraciones privadas de la implementación.

https://github.com/Jr130797/CESE_TSSE-TP3/blob/a01a2318e5d214baebfa0f114a975cac7027d3f3/src/leds.h#L10-L13

**Comment by Jr130797** [comment]
Corregido
